name 'cerny'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures cerny'
long_description 'Installs/Configures cerny'
version '0.3.4'

supports 'redhat'

depends 'chef-server'
depends 'chef-server-ctl'
depends 'firewalld'
depends 'chef-vault'
depends 'chef-analytics'
depends 'supermarket-omnibus-cookbook'
